//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace morimori.TScore.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("morimori.TScore.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Can I delete it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlertDelete {
            get {
                return ResourceManager.GetString("AlertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attention に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttentionMessage {
            get {
                return ResourceManager.GetString("AttentionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doubles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Doubles {
            get {
                return ResourceManager.GetString("Doubles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter game count. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorGameCount {
            get {
                return ResourceManager.GetString("ErrorGameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the game name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorGameName {
            get {
                return ResourceManager.GetString("ErrorGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a player name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorPlayerName {
            get {
                return ResourceManager.GetString("ErrorPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match venue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GamePlace {
            get {
                return ResourceManager.GetString("GamePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MyName {
            get {
                return ResourceManager.GetString("MyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewEntry {
            get {
                return ResourceManager.GetString("NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not yet entered に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotYetEnteredMessage {
            get {
                return ResourceManager.GetString("NotYetEnteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pair name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PairName {
            get {
                return ResourceManager.GetString("PairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name of rival に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RivalName {
            get {
                return ResourceManager.GetString("RivalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Set1 {
            get {
                return ResourceManager.GetString("Set1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Set2 {
            get {
                return ResourceManager.GetString("Set2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Set3 {
            get {
                return ResourceManager.GetString("Set3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Set4 {
            get {
                return ResourceManager.GetString("Set4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Set5 {
            get {
                return ResourceManager.GetString("Set5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Singles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Singles {
            get {
                return ResourceManager.GetString("Singles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tournament に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
